version: '3'
services:
  mysql:
    container_name: mysql_comp_test
    image: mysql:5.7
    ports:
      - 3333:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db:/var/lib/mysql
  phpmyadmin:
      container_name: phpmyadmin_comp_test
      image: phpmyadmin/phpmyadmin
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
        - PMA_USER=root
        - PMA_PASSWORD=password
      links:
        - mysql
      ports:
        - 8080:80
      volumes:
        - /sessions
  php:
    container_name: php_apache_comp_test
    build: ./php
    ports:
      - 8000:80
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mysql
volumes:
  db:
